# This workflow installs the latest version of Terraform CLI and configures the Terraform CLI configuration file
# with an API token for Terrafeorm Cloud (app.terraform.io). On pull request events, this workflow will run
# `terraform init`, `terraform fmt`, and `terraform plan` (speculsative plan via Terraform Cloud). On push events
# to the "main" branch, `terraform apply` will be executed.
name: 'Terraform'

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set Environment Variables
      env:
        GODADDY_API_KEY: ${{ secrets.GODADDY_API_KEY }}
        GODADDY_API_SECRET: ${{ secrets.GODADDY_API_SECRET }}
      run: |
        echo "Environment variables set"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::864899850759:role/knab-lab-tf-github-to-aws
        aws-region: eu-central-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Terraform Apply
      run: terraform apply --var-file prod.tfvars -auto-approve -input=false
